/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfase;

import Builder.DatosDirector;
import Variables.AtributosSistema;
import CargaDatosExcel.CargaExcelImp;
import Factory.FactoryImp;
import Factory.FactoryImplementacion;
import Strategia.MetodosCalculoDistanciaImp;
import Strategia.MetodosCalculoEmisionImp;
import Builder.SalidaExcel;
import Builder.SalidaBuilder;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import CargaDatosExcel.CargaExcel;
import Builder.SalidaCsv;
import java.awt.Image;
import java.awt.Toolkit;
import static Constantes.Constantes.datos;
  
/**
 *
 * @author Ingenieria
 */
public class JPanelElementos extends javax.swing.JFrame implements ConstantesInterfase {

    /**
     * Creates new form JPanelElementos
     */
    private JFileChooser seleccionar = new JFileChooser();
    private File archivo;
    private FactoryImplementacion factoryImp = new FactoryImp();

    public JPanelElementos() {
        this.setBounds(350, 350, 400, 400);
        this.setSize(ancho, alto);
        this.setTitle(tituloDatos);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.jTextField1_NumeroProvedores.setText("0");
//        this.jTextField2_CpaVehiculo.setText("240000");
//        this.jTextField3_CapVolumen.setText("100");
//        this.jTextField4_CargaMin.setText("1000");
//        this.jTextField5_ProRuta.setText("2");
//        this.jTextKilometrosDesviar.setText("50");
        initComponents();
        setTitle("Carga de datos");
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/shopping-list.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1_NumeroProvedores = new javax.swing.JTextField();
        jLabel1_numeroProvedores = new javax.swing.JLabel();
        jLabel2_CapVehiculo = new javax.swing.JLabel();
        jLabel3_CapVolumen = new javax.swing.JLabel();
        jLabel4_CargaMIn = new javax.swing.JLabel();
        jLabel5_ProRuta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2_CpaVehiculo = new javax.swing.JTextField();
        jTextField3_CapVolumen = new javax.swing.JTextField();
        jTextField4_CargaMin = new javax.swing.JTextField();
        jTextField5_ProRuta = new javax.swing.JTextField();
        jTextKilometrosDesviar = new javax.swing.JTextField();
        jButton1_SubirExcel = new javax.swing.JButton();
        jButton2_GenerarExcel = new javax.swing.JButton();
        jComboBox1_Metodos = new javax.swing.JComboBox<>();
        jLabel1_metodos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1_NumeroProvedores.setText("0");

        jLabel1_numeroProvedores.setText("Numero Provedores:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carga Información");
        setIconImage(getIconImage());

        jLabel2_CapVehiculo.setText("Capacidad Vehiculo:");

        jLabel3_CapVolumen.setText("Capacidad Volumen:");

        jLabel4_CargaMIn.setText("Cargar minima:");

        jLabel5_ProRuta.setText("Provedores por Ruta:");

        jLabel6.setText("Kilometros a desviar");

        jTextField2_CpaVehiculo.setText("24000");

        jTextField3_CapVolumen.setText("100");

        jTextField4_CargaMin.setText("1000");

        jTextField5_ProRuta.setText("4");

        jTextKilometrosDesviar.setText("50");

        jButton1_SubirExcel.setText("Subir Excel");
        jButton1_SubirExcel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 255, 153)));
        jButton1_SubirExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SubirExcelActionPerformed(evt);
            }
        });

        jButton2_GenerarExcel.setText("Generar Excel");
        jButton2_GenerarExcel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        jButton2_GenerarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_GenerarExcelActionPerformed(evt);
            }
        });

        jComboBox1_Metodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distancia", "Emision" }));
        jComboBox1_Metodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_MetodosActionPerformed(evt);
            }
        });

        jLabel1_metodos.setText("Seleccionar Método");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenP.png"))); // NOI18N
        jLabel2.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2_CapVehiculo)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4_CargaMIn)
                                            .addComponent(jLabel3_CapVolumen)))
                                    .addComponent(jLabel5_ProRuta)
                                    .addComponent(jLabel1_metodos)
                                    .addComponent(jLabel6))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2_CpaVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jTextField3_CapVolumen, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jTextField4_CargaMin, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jTextField5_ProRuta)
                                    .addComponent(jComboBox1_Metodos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextKilometrosDesviar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_SubirExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(jButton2_GenerarExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_CapVehiculo)
                    .addComponent(jTextField2_CpaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_CapVolumen)
                    .addComponent(jTextField3_CapVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4_CargaMIn)
                    .addComponent(jTextField4_CargaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5_ProRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5_ProRuta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_metodos)
                    .addComponent(jComboBox1_Metodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextKilometrosDesviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_SubirExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_GenerarExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_SubirExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SubirExcelActionPerformed
        try {
            if (seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
                archivo = seleccionar.getSelectedFile();
                JOptionPane.showMessageDialog(null, "Archivo Cargado con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Archivo no reconocido " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1_SubirExcelActionPerformed

    private void jButton2_GenerarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_GenerarExcelActionPerformed
        //carga minima : cuando tiene igual o menor a esa carga minima mensaje centro consolidacion
        //provedores por ruta: indica el numero maximo de provedores que puede contener una ruta expecifica 
        //kilometros maximos a desviarse: distacia de punto a punto debe ser menor al valor indicado 
        System.out.println(jComboBox1_Metodos.getSelectedIndex());
        DatosDirector datosDirector = new DatosDirector();
        if (!"".equals(jTextField2_CpaVehiculo.getText()) && !"".equals(jTextField3_CapVolumen.getText()) && archivo != null) {
            switch (jComboBox1_Metodos.getSelectedIndex()) {
                case 0: {
                    if (factoryImp.inicioMetodos(new CargaExcelImp(archivo.getPath(), Integer.parseInt(jTextField1_NumeroProvedores.getText())))) {
                        if (factoryImp.inicioMetodos(new MetodosCalculoDistanciaImp(Double.parseDouble(jTextField3_CapVolumen.getText()), Double.parseDouble(jTextField2_CpaVehiculo.getText()), Double.parseDouble(jTextField4_CargaMin.getText()), Double.parseDouble(jTextField5_ProRuta.getText()), Double.parseDouble(jTextKilometrosDesviar.getText())))) {
                            switch ("Excel") {
                                case "Excel": {
                                    try {
                                        datosDirector.setSalidaBuilder(new SalidaExcel());
                                        datosDirector.creacionSalida();
                                        JOptionPane.showMessageDialog(null, "Excel generado", "Exito", JOptionPane.INFORMATION_MESSAGE);
                                        int input = JOptionPane.showConfirmDialog(null, "Generar nuevo excel", "Información", JOptionPane.INFORMATION_MESSAGE);
                                        switch (input) {
                                            case 0: {
                                                archivo = null;
                                                datos.IniciarSistema();
                                                JOptionPane.showMessageDialog(null, "Digite nuevamente los datos", "Información", JOptionPane.INFORMATION_MESSAGE);
                                                break;
                                            }
                                            case 1: {
                                                dispose();
                                                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                                break;
                                            }
                                            case 2: {
                                                dispose();
                                                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                                break;
                                            }
                                            default: {
                                                dispose();
                                                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                            }
                                        }
                                        System.out.println(input);
                                        break;
                                    } catch (Exception e) {
                                        JOptionPane.showMessageDialog(null, "Error al generar el excel" + e, "Error", JOptionPane.ERROR_MESSAGE);
                                    }

                                }
                                default:
                                    JOptionPane.showMessageDialog(null, "Se presento un problema al generar el excel", "Error", JOptionPane.ERROR_MESSAGE);
                                    dispose();
                                    break;
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Se presento un problema al generar el excel", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Problema a carga datos", "Error", JOptionPane.ERROR_MESSAGE);
                    }

                    break;
                }
                case 1: {
                    if (factoryImp.inicioMetodos(new CargaExcelImp(archivo.getPath(), Integer.parseInt(jTextField1_NumeroProvedores.getText())))) {
                        if (factoryImp.inicioMetodos(new MetodosCalculoEmisionImp(Double.parseDouble(jTextField3_CapVolumen.getText()), Double.parseDouble(jTextField2_CpaVehiculo.getText()), Double.parseDouble(jTextField4_CargaMin.getText()), Double.parseDouble(jTextField5_ProRuta.getText()), Double.parseDouble(jTextKilometrosDesviar.getText())))) {
                            switch ("Excel") {
                                case "Excel": {
                                    try {
                                        datosDirector.setSalidaBuilder(new SalidaExcel());
                                        datosDirector.creacionSalida();
                                        JOptionPane.showMessageDialog(null, "Excel generado", "Exito", JOptionPane.INFORMATION_MESSAGE);
                                        int input = JOptionPane.showConfirmDialog(null, "Generar nuevo excel", "Información", JOptionPane.INFORMATION_MESSAGE);
                                        switch (input) {
                                            case 0: {
                                                archivo = null;
                                                datos.IniciarSistema();
                                                JOptionPane.showMessageDialog(null, "Digite nuevamente los datos", "Información", JOptionPane.INFORMATION_MESSAGE);
                                                break;
                                            }
                                            case 1: {
                                                dispose();
                                                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                                break;
                                            }
                                            case 2: {
                                                dispose();
                                                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                                break;
                                            }
                                            default: {
                                                dispose();
                                                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                            }
                                        }
                                        System.out.println(input);
                                        break;
                                    } catch (Exception e) {
                                        JOptionPane.showMessageDialog(null, "Error al generar el excel" + e, "Error", JOptionPane.ERROR_MESSAGE);
                                    }

                                }
                                default:
                                    JOptionPane.showMessageDialog(null, "Se presento un problema al generar el excel", "Error", JOptionPane.ERROR_MESSAGE);
                                    dispose();
                                    break;
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Se presento un problema al generar el excel", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Problema a carga datos", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                }
                default: {
                    JOptionPane.showMessageDialog(null, "Problema en la aplicación", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falta información", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2_GenerarExcelActionPerformed

    private void jComboBox1_MetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_MetodosActionPerformed
        String categoria1 = (String) jComboBox1_Metodos.getSelectedItem();
        if (categoria1.equalsIgnoreCase("emision")) {
            jTextKilometrosDesviar.setEnabled(false);
        } else {
            jTextKilometrosDesviar.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1_MetodosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_SubirExcel;
    private javax.swing.JButton jButton2_GenerarExcel;
    private javax.swing.JComboBox<String> jComboBox1_Metodos;
    private javax.swing.JLabel jLabel1_metodos;
    private javax.swing.JLabel jLabel1_numeroProvedores;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_CapVehiculo;
    private javax.swing.JLabel jLabel3_CapVolumen;
    private javax.swing.JLabel jLabel4_CargaMIn;
    private javax.swing.JLabel jLabel5_ProRuta;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1_NumeroProvedores;
    private javax.swing.JTextField jTextField2_CpaVehiculo;
    private javax.swing.JTextField jTextField3_CapVolumen;
    private javax.swing.JTextField jTextField4_CargaMin;
    private javax.swing.JTextField jTextField5_ProRuta;
    private javax.swing.JTextField jTextKilometrosDesviar;
    // End of variables declaration//GEN-END:variables
}
